import matplotlib.pyplot as plt
import numpy as np
import os
from main2 import TIME_DURATION
lib_path = os.path.abspath('/home/andrea/ros_simulation_ws/src/ipp_pkg/src/logs/plot')

#LOAD LOG FILES
ekf_y = np.loadtxt(lib_path+'/target_est_y.txt')
real_y = np.loadtxt(lib_path+'/target_y_traj.txt')
ekf_x = np.loadtxt(lib_path+'/target_est_x.txt')
real_x = np.loadtxt(lib_path+'/target_x_traj.txt')
err_x = np.loadtxt(lib_path+'/rmse_y.txt')
err_y = np.loadtxt(lib_path+'/rmse_x.txt')
s_x = np.loadtxt(lib_path+'/x_platform.txt')
s_y = np.loadtxt(lib_path+'/y_platform.txt')
auv1_x = np.loadtxt(lib_path+'/auv1_x.txt')
auv1_y = np.loadtxt(lib_path+'/auv1_y.txt')
auv2_x = np.loadtxt(lib_path+'/auv2_x.txt')
auv2_y = np.loadtxt(lib_path+'/auv2_y.txt')
opt_est_x = np.loadtxt(lib_path+'/target_traj_est_x.txt')
opt_est_y = np.loadtxt(lib_path+'/target_traj_est_y.txt')
opt_real_x = np.loadtxt(lib_path+'/target_traj_real_x.txt')
opt_real_y = np.loadtxt(lib_path+'/target_traj_real_y.txt')
ctrl_cmds = np.loadtxt(lib_path+'/plot_cmds.txt')
# PLOT
n_sample = np.size(ekf_y)
t = np.linspace(0,TIME_DURATION,n_sample)
plt.subplot(3,1,1)
plt.plot(t,ekf_y[0:n_sample],'g')
plt.plot(t,real_y[0:n_sample],'r--')
plt.xlabel('time(s)')
plt.ylabel('y pos target (m)')
plt.legend(['estimated','real'])
plt.grid()
plt.subplot(3,1,2)
plt.plot(t,ekf_x[0:n_sample],'g')
plt.plot(t,real_x[0:n_sample],'r--')

plt.xlabel('time (s)')
plt.ylabel('x pos target (m)')
plt.legend(['estimated','real'])
plt.grid()
plt.subplot(3,1,3)
plt.plot(ekf_x[0:n_sample],ekf_y[0:n_sample])
plt.plot(real_x[0:n_sample],real_y[0:n_sample])
plt.xlabel('x pos target (m)')
plt.ylabel('y pos target (m)')
plt.legend(['estimated','real'])
plt.xlim([0,5000])
plt.grid()
plt.show()

plt.plot(s_x,s_y)
plt.plot(real_x,real_y)
plt.plot(auv1_x,auv1_y,'r',linewidth=1)
plt.plot(auv2_x,auv2_y,'g',linewidth=1)

plt.xlabel('x platform (m)')
plt.ylabel('y platform (m)')
circle1 = plt.Circle((2000,0),50,color='m')
circle2 = plt.Circle((real_x[0],real_y[0]),25,color='y')
circle3 = plt.Circle((s_x[0],s_y[0]),25,color='b')
circle4 = plt.Circle((auv1_x[0],auv1_y[0]),25,color='r')
circle5 = plt.Circle((auv2_x[0],auv2_y[0]),25,color='g')
plt.xlim([0,8000])
plt.gca().add_patch(circle1)
plt.gca().add_patch(circle2)
plt.gca().add_patch(circle3)
plt.gca().add_patch(circle5)
plt.gca().add_patch(circle4)
plt.legend(['platform path','target path','AUV1 path','AUV2 path','base',
'target start','platform start','AUV1 start','AUV2 start'])
plt.grid()
plt.show()

# FOR SEE IF optimization is processin the target well ( just checl if the target estimation and path is similar to prev plot)
plt.plot(opt_est_x,opt_est_y)
plt.plot(opt_real_x,opt_real_y)
plt.xlim([0,8000])
plt.ylim([0,11000])
plt.title(['OPTIMIZATION TARGET PREDICTION'])
plt.xlabel('x pos target (m)')
plt.ylabel('y pos target (m)')
plt.legend(['estimated','real'])
plt.grid()
plt.show()
#PLOT ctrl cmds from optimization
n_sample1 = np.size(ctrl_cmds)
t1 = np.linspace(0,TIME_DURATION,n_sample1)
plt.plot(t1,ctrl_cmds,'-ok','black',markerfacecolor='red')
plt.xlim([0,TIME_DURATION/4])
plt.grid()
plt.show()


plt.plot(t,err_x[0:n_sample])
plt.plot(t,err_y[0:n_sample])
plt.legend(['error x target pos','error y target pos'])
plt.xlabel('time (s)')
plt.ylabel('RMSE')
plt.grid()
plt.show()

