from turtle import width
import matplotlib.pyplot as plt
import numpy as np
import os
from main2 import TIME_DURATION
lib_path = os.path.abspath('/home/andrea/ros_simulation_ws/src/ipp_pkg/src/logs/plot')

#LOAD LOG FILES
# Estimation vs Real (in time)
ekf_y_on = np.loadtxt(lib_path+'/target_est_y_ON.txt')
ekf_x_on = np.loadtxt(lib_path+'/target_est_x_ON.txt')

real_y = np.loadtxt(lib_path+'/target_y_traj.txt')
real_x = np.loadtxt(lib_path+'/target_x_traj.txt')

ekf_y_off = np.loadtxt(lib_path+'/target_est_y_OFF.txt')
ekf_x_off = np.loadtxt(lib_path+'/target_est_x_OFF.txt')
# RMSE optimization ON vs OFF
err_y_on = np.loadtxt(lib_path+'/rmse_y_ON.txt')
err_x_on = np.loadtxt(lib_path+'/rmse_x_ON.txt')
err_y_off = np.loadtxt(lib_path+'/rmse_y_OFF.txt')
err_x_off = np.loadtxt(lib_path+'/rmse_x_OFF.txt')
# Platform and AUV path OFF vs ON
s_x_on = np.loadtxt(lib_path+'/x_platform_ON.txt')
s_y_on = np.loadtxt(lib_path+'/y_platform_ON.txt')
auv1_x_on = np.loadtxt(lib_path+'/auv1_x_ON.txt')
auv1_y_on = np.loadtxt(lib_path+'/auv1_y_ON.txt')
auv2_x_on = np.loadtxt(lib_path+'/auv2_x_ON.txt')
auv2_y_on = np.loadtxt(lib_path+'/auv2_y_ON.txt')

s_x_off = np.loadtxt(lib_path+'/x_platform_OFF.txt')
s_y_off = np.loadtxt(lib_path+'/y_platform_OFF.txt')
auv1_x_off = np.loadtxt(lib_path+'/auv1_x_OFF.txt')
auv1_y_off = np.loadtxt(lib_path+'/auv1_y_OFF.txt')
auv2_x_off = np.loadtxt(lib_path+'/auv2_x_OFF.txt')
auv2_y_off = np.loadtxt(lib_path+'/auv2_y_OFF.txt')
# Optimization module data (ctrl_cmds, estimation ...) for DEBUGGING PURPOSE
opt_est_x = np.loadtxt(lib_path+'/target_traj_est_x.txt')
opt_est_y = np.loadtxt(lib_path+'/target_traj_est_y.txt')
opt_real_x = np.loadtxt(lib_path+'/target_traj_real_x.txt')
opt_real_y = np.loadtxt(lib_path+'/target_traj_real_y.txt')
ctrl_cmds = np.loadtxt(lib_path+'/plot_cmds.txt')
# PLOT
n_sample = np.size(ekf_y_on)
t = np.linspace(0,TIME_DURATION,n_sample)
plt.subplot(2,1,1)
plt.plot(t,ekf_y_on[0:n_sample],'g')
plt.plot(t,real_y[0:n_sample],'r--')
plt.title('TARGET ESTIMATION ALONG Y-AXIS - COMPARISON')
plt.xlabel('time(s)')
plt.ylabel('y pos target (m)')
plt.legend(['optimization ON','real'])
plt.grid()

plt.subplot(2,1,2)
plt.plot(t,ekf_y_off[0:n_sample],'b')
plt.plot(t,real_y[0:n_sample],'r--')
plt.xlabel('time(s)')
plt.ylabel('y pos target (m)')
plt.legend(['optimization OFF','real'])
plt.grid()
plt.show()

plt.subplot(2,1,1)
plt.plot(t,ekf_x_on[0:n_sample],'g')
plt.plot(t,real_x[0:n_sample],'r--')
plt.title('TARGET ESTIMATION ALONG X-AXIS - COMPARISON')
plt.xlabel('time(s)')
plt.ylabel('x pos target (m)')
plt.legend(['optimization ON','real'])
plt.grid()

plt.subplot(2,1,2)
plt.plot(t,ekf_x_off[0:n_sample],'b')
plt.plot(t,real_x[0:n_sample],'r--')
plt.xlabel('time(s)')
plt.ylabel('x pos target (m)')
plt.legend(['optimization OFF','real'])
plt.grid()
plt.show()

plt.plot(s_x_on,s_y_on)
plt.plot(real_x,real_y)
plt.plot(auv1_x_on,auv1_y_on,'r',linewidth=2)
plt.plot(auv2_x_on,auv2_y_on,'g',linewidth=2)
plt.title('SIMULATION')
plt.xlabel('x (m)')
plt.ylabel('y (m)')
circle1 = plt.Circle((2000,0),50,color='m')
circle2 = plt.Circle((real_x[0],real_y[0]),25,color='y')
circle3 = plt.Circle((s_x_on[0],s_y_on[0]),25,color='b')
circle4 = plt.Circle((auv1_x_on[0],auv1_y_on[0]),25,color='r')
circle5 = plt.Circle((auv2_x_on[0],auv2_y_on[0]),25,color='g')

plt.gca().add_patch(circle1)
plt.gca().add_patch(circle2)
plt.gca().add_patch(circle3)
plt.gca().add_patch(circle5)
plt.gca().add_patch(circle4)
plt.legend(['platform path','target path','AUV1 path','AUV2 path','base',
'target start','platform start','AUV1 start','AUV2 start'])
plt.grid()
plt.show()

plt.plot(s_x_off,s_y_off)
plt.plot(real_x,real_y)
plt.plot(auv1_x_off,auv1_y_off,'r',linewidth=2)
plt.plot(auv2_x_off,auv2_y_off,'g',linewidth=2)
plt.title('SIMULATION')
plt.xlabel('x (m)')
plt.ylabel('y (m)')
circle1 = plt.Circle((2000,0),50,color='m')
circle2 = plt.Circle((real_x[0],real_y[0]),25,color='y')
circle3 = plt.Circle((s_x_off[0],s_y_off[0]),25,color='b')
circle4 = plt.Circle((auv1_x_off[0],auv1_y_off[0]),25,color='r')
circle5 = plt.Circle((auv2_x_off[0],auv2_y_off[0]),25,color='g')

plt.gca().add_patch(circle1)
plt.gca().add_patch(circle2)
plt.gca().add_patch(circle3)
plt.gca().add_patch(circle5)
plt.gca().add_patch(circle4)
plt.legend(['platform path','target path','AUV1 path','AUV2 path','base',
'target start','platform start','AUV1 start','AUV2 start'])
plt.grid()
plt.show()

# FOR SEE IF optimization is processin the target well ( just checl if the target estimation and path is similar to prev plot)
#plt.plot(opt_est_x,opt_est_y)
'''plt.plot(opt_real_x,opt_real_y,'o')
plt.title(['OPTIMIZATION TARGET PREDICTION'])
plt.xlabel('x pos target (m)')
plt.ylabel('y pos target (m)')
plt.legend(['estimated','real'])
plt.grid()
plt.show()'''

#PLOT ctrl cmds from optimization
n_sample1 = np.size(ctrl_cmds)
print(n_sample1)
t1 = np.linspace(0,TIME_DURATION,n_sample1)
plt.plot(t1,ctrl_cmds,'-ok',markerfacecolor='red')
plt.xlim([0,TIME_DURATION/4])
plt.grid()
plt.show()

plt.subplot(2,1,1)
plt.plot(t,err_x_on[0:n_sample])
plt.plot(t,err_x_off[0:n_sample])
plt.legend(['optimization ON','optimization OFF'])
plt.title(['ESTIMATION ERROR ALONG X-AXIS'])
plt.xlabel('time (s)')
plt.ylabel('RMSE')
plt.grid()
plt.subplot(2,1,2)
plt.plot(t,err_y_on[0:n_sample])
plt.plot(t,err_y_off[0:n_sample])
plt.legend(['optimization ON','optimization OFF'])
plt.title(['ESTIMATION ERROR ALONG Y-AXIS'])
plt.xlabel('time (s)')
plt.ylabel('RMSE')
plt.grid()
plt.show()

